### ISSUE TITLE
[FEAT] 펫 보관함 화면 서버 연동 구현 & 테스트

### ISSUE THREAD

**Issue by kkk5474096** [ddan-dda-ra/ddan-ddan-android#21]
## 💡 Issue

펫 보관함 화면 서버 연동 구현 & 테스트

## 📝 todo

- [ ] 테스트 토큰으로 테스트 진행
- [ ] 서버 연동 구현
- [ ] MVI 구조로 구현
