### ISSUE TITLE
[FEAT] 홈 화면 API 연결 & 구조 변경

### ISSUE THREAD

**Issue by kkk5474096** [ddan-dda-ra/ddan-ddan-android#24]
## 💡 Issue

홈 화면 API 연결 & 구조 변경

## 📝 todo

- [x] 먹이주기 API 연동
- [x] 놀아주기 API 연동
- [x] 현재 상태(내 정보 & 펫 상태) API 연동
- [x] MVI 구조 변경
