### ISSUE TITLE
[FEAT] 내 정보 수정 api 연결

### ISSUE THREAD

**Issue by blueme0** [ddan-dda-ra/ddan-ddan-android#29]
## 💡 Issue
회원가입 시나리오를 위한. . . 내 정보 수정 api 연결

## 📝 todo

- [x] 내 정보 수정 api 연결
- [x] 펫 뽑기 (type 지정) api 연결
- [x] 펫 뽑기 이후 메인 펫 설정
- [ ] 카카오 로그인 로직 분리
