### ISSUE TITLE
[FEAT] 회원탈퇴 변경사항 반영

### ISSUE THREAD

**Issue by kkk5474096** [ddan-dda-ra/ddan-ddan-android#71]
## 💡 Issue

회원탈퇴 변경사항 반영

## 📝 todo

- [ ] 회원탈퇴 변경사항 반영
- [ ] 탈퇴 이유 body 추가
- [ ] 기타 오류 수정
