### ISSUE TITLE
[FEAT] 회원가입 UI 반영

### ISSUE THREAD

**Issue by blueme0** [ddan-dda-ra/ddan-ddan-android#77]
## 💡 Issue

회원가입 UI 반영

## 📝 todo

- [x] 회원가입 완료 시 로티 적용
- [x] 온보딩 이미지 적용
- [x] 약관 링크 적용
